[package]
name = "program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
types = { path = "../types" }
serde = { version = "*", default-features = false, features = ["derive"] }
serde_json = "1"
